version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_BACK_END_BASE_URL=${VITE_BACK_END_BASE_URL}
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiOTZiNGY0ODU5NGU5NDgyYmFhZjBjZGY0ODJiZGY4MzMiLCJ0IjoiNDVlMjk4ZGEtOGY5ZC00NzQzLWFkNmUtYTFkYThiYjA4YWYzIiwicyI6IlpUSmpOemRrTVdFdE5tUXlZUzAwWlRneExUZ3hPREV0WW1NNU16WTVPVEE0TjJWayJ9
