version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACK_END_BASE_URL=${VITE_BACK_END_BASE_URL}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiOTZiNGY0ODU5NGU5NDgyYmFhZjBjZGY0ODJiZGY4MzMiLCJ0IjoiNjhhOGNjMDktYWUyYy00ZDk4LWI0NjMtOGE5N2FmZmZiYjk5IiwicyI6Ik1URXhNVEZqWmpJdE0ySmxNQzAwWlRVNExXSXlOVFl0T1dReFlqZG1OVEF3TWpRdyJ9
