name: Deploy to Staging (Master Branch)

on:
  push:
    branches: ["master"]

jobs:
  deploy-staging:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for staging
        run: |
          echo "VITE_BACK_END_BASE_URL=${{ secrets.VITE_BACK_END_BASE_URL }}" > .env.staging

      - name: Deploy to Staging using Docker Compose
        run: |
          docker compose -f docker-compose-staging.yml down || true
          docker compose -f docker-compose-staging.yml --env-file .env.staging up -d --build
