name: Deploy to Staging

on:
  push:
    branches: ["master"]

jobs:
  deploy-staging:
    runs-on: self-hosted
    # environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for staging
        env:
          VITE_BACK_END_BASE_URL: ${{ secrets.VITE_BACK_END_BASE_URL }}
        run: |
          echo "VITE_BACK_END_BASE_URL=${VITE_BACK_END_BASE_URL}" > .env.staging

      - name: Stop existing staging containers
        run: |
          docker compose -f docker-compose-staging.yml down || true

      - name: Clean up old images
        run: |
          docker image prune -f

      - name: Deploy to Staging
        run: |
          docker compose -f docker-compose-staging.yml --env-file .env.staging up -d --build

      - name: Health check
        run: |
          sleep 30
          curl -f http://localhost:3000 || exit 1

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Staging deployment successful"
          else
            echo "❌ Staging deployment failed"
          fi
